# -*- coding: utf-8 -*-
"""Number Modification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQbkV8tf0vj8e07xa_0YjyJyjwaOi9NL
"""

import random
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

def num_mod(text):
  # Membagi kalimat menjadi token
  words = word_tokenize(text)

  # Mengubah angka yang terdapat dalam kalimat
  for i, word in enumerate(words):
      if word.isdigit():
          num = int(word)
          # Mendapatkan angka secara random antara (number/2) ~ (number*2)
          num = random.randint(int(num/2), int(num*2))
          words[i] = str(num)

  # Menggantikan angka awal menjadi angka baru yang sudah dimanipulasi
  text_modified = " ".join(words)

  return text_modified

text = 'Terdapat 5 ekor ikan koi yang sedang berenang dan dikerjar oleh 2 ekor kucing.'
text_modified = num_mod(text)
print(text_modified)